---
# Mirrors the following content which is REQUIRED to install Maximo Application Suite Core Services:
# 1. IBM Db2 Universal Operator
# 2. IBM Maximo IoT
#
# This playbook aligns with the ibm.mas_devops.oneclick_add_iot playbook

- hosts: localhost
  any_errors_fatal: true

  vars:
    catalog_tag: "{{ lookup('env', 'MAS_CATALOG_VERSION') | default ('v8-220717', True) }}"

    mirror_db2u: "{{ lookup('env', 'MIRROR_DB2U') | default ('True', True) | bool }}"
    mirror_mas_iot: "{{ lookup('env', 'MIRROR_MAS_IOT') | default ('True', True) | bool }}"

  pre_tasks:
    # Note that REGISTRY_USERNAME and REGISTRY_PASSWORD are not required.
    # They are only needed if you have set up authentication on your private registry
    - name: Check for required environment variables
      assert:
        that:
          - lookup('env', 'REGISTRY_PUBLIC_HOST') != ""
          - lookup('env', 'REGISTRY_PUBLIC_PORT') != ""
          - lookup('env', 'IBM_ENTITLEMENT_KEY') != ""
        fail_msg: "One or more required environment variables are not defined"
    - name: Load CASE bundle versions
      include_vars:
        file: "{{ playbook_dir }}/../common_vars/casebundles/{{ catalog_tag }}.yml"

  roles:
    # 1. IBM Db2u
    # -------------------------------------------------------------------------
    - name: ibm.mas_airgap.case_prepare
      when: mirror_db2u
      vars:
        case_name: ibm-db2uoperator
        case_version: "{{ db2u_version }}"
        exclude_images: []

    - name: ibm.mas_airgap.case_mirror
      when: mirror_db2u
      vars:
        case_name: ibm-db2uoperator
        case_version: "{{ db2u_version }}"
        case_inventory_name: "db2uOperatorSetup"


    # 2. IBM Maximo IoT
    # -------------------------------------------------------------------------
    - name: ibm.mas_airgap.case_prepare
      when: mirror_mas_iot
      vars:
        case_name: ibm-mas-iot
        case_version: "{{ mas_iot_version }}"
        exclude_images: []

    - name: ibm.mas_airgap.case_mirror
      when: mirror_mas_iot
      vars:
        case_name: ibm-mas-iot
        case_version: "{{ mas_iot_version }}"
        case_inventory_name: "ibmMasIotSetup"
